build: off

install:
  # unfortunately, `commitId` in hooks is abbreviated and we can't work with that for Upsource
  # set a custom message as the full commit ID. This *has* to be the first job given the way
  # our service is designed, please don't move.
  - ps: Add-AppveyorMessage $env:APPVEYOR_REPO_COMMIT
  - ps: Install-Product node 10 x64
  - yarn install --frozen-lockfile --check-files
  - yarn lint
  - yarn compile:ci

test_script:
  - yarn test-flaky
  # - yarn screentest
  # - 7z a screentest.zip test-dist\screentest\*
  # - ps: $env:warning_ico = ":warning:"
  # - ps: $env:success_ico = ":white_check_mark:"
  # - ps: $env:changed_screens = (Get-Content -Raw -Path test-dist\screentest\state.json | ConvertFrom-Json).changedScreens
  # - ps: $env:project_link = "https://ci.appveyor.com/project/Streamlabs/streamlabs-obs"
  # - ps: If ($env:changed_screens -gt 0) {Add-AppveyorMessage "$env:warning_ico $env:changed_screens screens have been changed $env:project_link/build/$env:APPVEYOR_BUILD_VERSION/artifacts"} else { Add-AppveyorMessage "$env:success_ico no screens changed" }

# artifacts:
#   - path: 'screentest.zip'
#     name: Screentests

notifications:
  - provider: GitHubPullRequest
    template: "{{#failed}}:x: build failed{{/failed}} {{#jobs}} {{#messages}} {{message}} {{/messages}} {{/jobs}}"
  # Build status to Upsource
  - provider: Webhook
    url: https://n2svzw3n4f.execute-api.us-east-1.amazonaws.com/dev/hooks/appveyor
    on_build_status_changed: true

cache:
  - plugins
